### ISSUE TITLE
コネクター説明ページにリンクするバナーを作成

### ISSUE THREAD

**Issue by soichiro-nitta** [soichiro-nitta/lrandcom#3]

**Comment by chikara-natsume** [comment]
ゆるーく、長く、そしてお互い気を使わない感じでつながって、なんか化学反応が起きたらおもしろいなというコミュニティを作りました。こちらから、ぜひご参加下さい！

**Comment by chikara-natsume** [comment]
ちょっと読みにくかったので、下記をバナーの文章を変更してもらえますか？

ゆるーく、長く、そしてお互い気を使わない感じでつながって、なんか化学反応が起きたらおもしろいなというコミュニティを作りました。こちらから、ぜひご参加下さい！

↓
(こちらに変更)
このサイトを通じて、ゆるーく、長く、つながれるコミュニティを作りました。こちらから、ぜひご参加下さい！

**Comment by soichiro-nitta** [comment]
@chikara-natsume 文章の変更、了解です！
