### ISSUE TITLE
記事の一番下のライター募集と記事制作のバナーの位置と色の変更

### ISSUE THREAD

**Issue by chikara-natsume** [soichiro-nitta/lrandcom#4]
<img width="506" alt="2017-07-08 10 07 54" src="https://user-images.githubusercontent.com/29973393/27981310-a12f5e1e-63c5-11e7-9076-d1485cbffcc2.png">

記事の一番下のところのライター募集の色と記事制作の色が同じなので、何か他の色はないですかね？？
あと、順番は記事制作が上でライター募集が下だと助かります。。

**Comment by soichiro-nitta** [comment]
@chikara-natsume 他の色考えてみます。順番了解しました。

イシュー作成ありがとうございます、助かります。こんな感じでやっていきましょう😁
